### ISSUE TITLE
ENOENT error

### ISSUE THREAD

**Issue by venuprasadnaik** [cowbell/ionic-geofence#34]
{ Error: ENOENT: no such file or directory, open 'E:\6th sem\Minor Project\revie
w 3\ionic-geofence-master\ionic-geofence-master\.env'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.config (E:\6th sem\Minor Project\review 3\ionic-geofence-master\io
nic-geofence-master\node_modules\dotenv\lib\main.js:30:37)
    at Object.<anonymous> (E:\6th sem\Minor Project\review 3\ionic-geofence-mast
er\ionic-geofence-master\gulpfile.js:13:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'E:\\6th sem\\Minor Project\\review 3\\ionic-geofence-master\\ionic-geof
ence-master\\.env' }

**Comment by tsubik** [comment]
You haven't created `.env` file, just `cp .env.sample .env` but I do not guarantee that sauce config there actually works.

**Comment by venuprasadnaik** [comment]
Thank you sir, it actually worked. But I am facing a problem after building the project. There is no problem after running "ionic serve". But the problem I got is after launching it to android. I am unable view the map on mobile but it is visible in localhost.
![screenshot_20170423-172800](https://cloud.githubusercontent.com/assets/13850765/25313368/b655aeb2-284a-11e7-8f22-0eac92e69980.png)
![screenshot 227](https://cloud.githubusercontent.com/assets/13850765/25313381/f77d2e2e-284a-11e7-84e8-90878c2f086a.png)
